<?php

namespace Waffler\OpenGen\Contracts;

use cebe\openapi\spec\OpenApi;

/**
 * Interface ReaderInterface.
 *
 * @author ErickJMenezes <erickmenezes.dev@gmail.com>
 */
interface InterfaceBuilder
{
    public const PHP_FILE_COMMENT = <<<EOL
This file is auto generated by Waffler OpenAPI Code generator package.

Do not modify unless you know exactly what you are doing.
EOL;

    public const DEFAULT_OPTIONS = [
        'interface_suffix' => 'ClientInterface',
        'namespace' => '',
    ];

    /**
     * @param \cebe\openapi\spec\OpenApi $specification
     *
     * @return array<\Nette\PhpGenerator\PhpFile>
     * @author ErickJMenezes <erickmenezes.dev@gmail.com>
     */
    public function buildInterface(OpenApi $specification): array;
}